### ISSUE TITLE
Compiling all of the `learn_metal` examples, except `00-window`, fails

### ISSUE THREAD

**Issue by yay** [odin-lang/examples#13]
@gingerBill Compiling all of the `learn_metal` examples, except `00-window`, fails with the following error:

```
[Running] odin run .
/Users/yay/projects/examples/learn_metal/01-primitive/01-primitive.odin(52:8) 'device' of type '^Device' has no field 'newRenderPipelineState'
```

Odin: both latest release and latest nightly (6b89ff43)
LLVM: 13.0.1
OS: macOS 12.3.1 (21E258) arm64

**Comment by yay** [comment]
It does work if I use `newRenderPipelineStateWithDescriptor`.

Inside of `Odin/vendor/darwin/Metal/MetalClasses.odin` I see:

```
@(objc_type=Device, objc_name="newRenderPipelineState")
Device_newRenderPipelineState :: proc{
	Device_newRenderPipelineStateWithDescriptorWithCompletionHandler,
	Device_newRenderPipelineStateWithDescriptor,
	Device_newRenderPipelineStateWithDescriptorWithOptionsAndCompletionHandler,
	Device_newRenderPipelineStateWithDescriptorWithReflection,
	Device_newRenderPipelineStateWithTileDescriptorWithCompletionHandler,
	Device_newRenderPipelineStateWithTileDescriptorWithReflection,
}
```

Is this a way to declare a bunch of overloaded functions and have the right one be called depending on the type and number of the parameters, that is not working for some reason?

**Comment by yay** [comment]
`05-perspective` example additionally fails to compile with `05-perspective.odin(258:20) 'device' of type '^Device' has no field 'newTexture'`

I had to replace it with: `depth_texture = device->newTextureWithDescriptor(desc)`

**Comment by Kelimion** [comment]
Merged the two Metal selector PRs (#12 & #14). Can you confirm this fixes the examples?

**Comment by yay** [comment]
@Kelimion It does. But I wonder if that is an issue with the compiler, as mentioned here https://github.com/odin-lang/examples/issues/13#issuecomment-1120221056?

**Comment by Kelimion** [comment]
> @Kelimion It does. But I wonder if that is an issue with the compiler, as mentioned here [#13 (comment)](https://github.com/odin-lang/examples/issues/13#issuecomment-1120221056)?

That is indeed how you declare a procedure group, aka explicit procedure overloading. Perhaps @gingerBill can take a gander to figure out why it didn't match as it did when he wrote these examples, but for now they work again by calling the specific proc.
