### ISSUE TITLE
the link to Odin's BSD-3 license is currently a 404 error

### ISSUE THREAD

**Issue by bg-thompson** [odin-lang/examples#33]
Line 5 of README.md contains the following markdown code:
```
[Odin's BSD-3 license](https://github.com/odin-lang/Odin/LICENSE)
```
The url here no longer links to an actual page with Odin's BSD-3 license; following the link gives a 404 error.

**Comment by Kelimion** [comment]
Fixed by #34. Thanks, Eric.
