### ISSUE TITLE
glfw/window/simple_window.odin does not link in Void Linux

### ISSUE THREAD

**Issue by chris-montero** [odin-lang/examples#60]
To reproduce:

1. On void linux, with the latest odin master branch compiler.
2. go to glfw/window/simple_window.odin
3. run `odin run .`
4. Get error:
```
/usr/bin/x86_64-unknown-linux-gnu-ld: cannot find -lglfw: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by laytan** [comment]
You need to install glfw from your package manager.

**Comment by chris-montero** [comment]
You're right, I forgot to install glfw-devel. Thanks.
